spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ebook-service
          uri: lb://ebook-service
          predicates:
            - Path=/ebook-service/**
        - id: payment-validation-service
          uri: lb://payment-validation-service
          predicates:
            - Path=/payment-validation-service/**
        - id: ebook-delivery-service
          uri: lb://ebook-delivery-service
          predicates:
            - Path=/ebook-delivery-service/**
management:
  tracing:
    sampling:
      probability: 1


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8060
